# Generated by Django 4.0.4 on 2022-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_delete_customaccountmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='access_level',
            field=models.IntegerField(choices=[(800, 'Super_admin'), (600, 'Company'), (400, 'Cargo_company')], db_column='AccessLevel', default=300),
        ),
    ]
