# Generated by Django 4.0.4 on 2022-04-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_role_access_level'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
    ]
