# Generated by Django 4.0.4 on 2022-04-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_role_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, db_column='RoleId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='Users.role'),
        ),
    ]
