# Generated by Django 4.0.4 on 2022-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='DeletedBy', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, db_column='DeletedOn')),
                ('status', models.BigIntegerField(db_column='Status', default=0, help_text='I will use this field for makingthe status like pending approved and for some other purpose by Default it is Zero which has no meaning')),
            ],
        ),
    ]
