# Generated by Django 4.0.4 on 2022-04-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_column='IsActive', default=True, help_text='I will use this for enable/disable a specific record')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to='Company.company')),
            ],
            options={
                'db_table': 'posts',
            },
            bases=('main.base',),
        ),
    ]
