# Generated by Django 4.0.2 on 2022-04-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('company_name', models.CharField(db_column='Company_Name', max_length=255)),
                ('company_email', models.EmailField(db_column='company_email', max_length=255, unique=True)),
                ('company_manager_name', models.CharField(db_column='Manager_Name', max_length=255)),
                ('company_address', models.CharField(db_column='Company_address', max_length=255)),
                ('about_company', models.TextField()),
                ('company_website', models.URLField()),
                ('is_active', models.BooleanField(db_column='IsActive', default=True, help_text='I will use this for enable/disable a specific record')),
            ],
            bases=('main.base',),
        ),
    ]
