# Generated by Django 4.0.4 on 2022-04-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(db_column='company_email', max_length=255, unique=True),
        ),
    ]
